"""create initial core tables

Revision ID: 116c1f30564e
Revises: 
Create Date: 2026-03-06 10:54:59.654007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '116c1f30564e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_rate_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('adapter_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange_symbol', sa.String(length=50), nullable=False),
    sa.Column('funding_rate', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('funding_interval_hours', sa.Integer(), nullable=True),
    sa.Column('predicted_funding_rate', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('mark_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('index_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('next_funding_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_funding_rate_snapshots_exchange_symbol_event_ts', 'funding_rate_snapshots', ['exchange', 'symbol', sa.literal_column('event_ts DESC')], unique=False)
    op.create_table('market_ticks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('adapter_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange_symbol', sa.String(length=50), nullable=False),
    sa.Column('bid_price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('ask_price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('mid_price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('bid_size', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('ask_size', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_ticks_exchange_symbol_event_ts', 'market_ticks', ['exchange', 'symbol', sa.literal_column('event_ts DESC')], unique=False)
    op.create_index('ix_market_ticks_symbol_event_ts', 'market_ticks', ['symbol', sa.literal_column('event_ts DESC')], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_events')
    op.drop_index('ix_market_ticks_symbol_event_ts', table_name='market_ticks')
    op.drop_index('ix_market_ticks_exchange_symbol_event_ts', table_name='market_ticks')
    op.drop_table('market_ticks')
    op.drop_index('ix_funding_rate_snapshots_exchange_symbol_event_ts', table_name='funding_rate_snapshots')
    op.drop_table('funding_rate_snapshots')
    # ### end Alembic commands ###
