"""add_funding_payments_table

Revision ID: 386b20f64042
Revises: d0967dce3eb8
Create Date: 2026-03-07 14:52:24.548317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386b20f64042'
down_revision: Union[str, Sequence[str], None] = 'd0967dce3eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('position_quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('mark_price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('funding_rate', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('accrued_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funding_payments')
    # ### end Alembic commands ###
