"""add_perp_position_fields_and_funding_accruals

Revision ID: 9f7b8a1c3d2e
Revises: 386b20f64042
Create Date: 2026-03-16 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f7b8a1c3d2e'
down_revision: Union[str, Sequence[str], None] = 'a3f9b1c2d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.
    
    Adds perp-related fields to position_snapshots:
    - position_type: 'spot' or 'perp' (defaults to 'spot' for existing rows)
    - contract_qty: number of contracts for perp positions
    - contract_size: size per contract in asset units
    - margin_posted: USD margin posted for perp positions
    
    Creates new funding_accruals table for tracking hourly funding payments.
    """
    # ### commands auto generated by Alembic - adjust as needed ###
    
    # Add new columns to position_snapshots
    op.add_column('position_snapshots', 
                  sa.Column('position_type', sa.String(length=20), nullable=False, server_default='spot'))
    op.add_column('position_snapshots', 
                  sa.Column('contract_qty', sa.Integer(), nullable=True))
    op.add_column('position_snapshots', 
                  sa.Column('contract_size', sa.Numeric(precision=28, scale=10), nullable=True))
    op.add_column('position_snapshots',
                  sa.Column('margin_posted', sa.Numeric(precision=28, scale=10), nullable=True))
    
    # Create funding_accruals table
    op.create_table('funding_accruals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('period_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('notional_usd', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('accrual_usd', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('settled', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjust as needed ###
    op.drop_table('funding_accruals')
    op.drop_column('position_snapshots', 'margin_posted')
    op.drop_column('position_snapshots', 'contract_size')
    op.drop_column('position_snapshots', 'contract_qty')
    op.drop_column('position_snapshots', 'position_type')
    # ### end Alembic commands ###
