"""add trading and risk core tables

Revision ID: d0967dce3eb8
Revises: 116c1f30564e
Create Date: 2026-03-06 11:11:17.167993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0967dce3eb8'
down_revision: Union[str, Sequence[str], None] = '116c1f30564e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnl_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('strategy_name', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('funding_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fee_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('snapshot_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('instrument_type', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('mark_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('leverage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('margin_used', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('snapshot_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('strategy_version', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('signal_strength', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('decision_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_signal_id', sa.UUID(), nullable=True),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('time_in_force', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('post_only', sa.Boolean(), nullable=False),
    sa.Column('client_order_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_signal_id'], ['strategy_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_intent_id', sa.UUID(), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=False),
    sa.Column('client_order_id', sa.String(length=100), nullable=True),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('submitted_qty', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('filled_qty', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('avg_fill_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('fees_paid', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fee_asset', sa.String(length=20), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_exchange_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['order_intent_id'], ['order_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fill_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_record_id', sa.UUID(), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange_trade_id', sa.String(length=100), nullable=True),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fill_qty', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fill_notional', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('liquidity_role', sa.String(length=20), nullable=True),
    sa.Column('fee_paid', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fee_asset', sa.String(length=20), nullable=True),
    sa.Column('fill_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_record_id'], ['order_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fill_records')
    op.drop_table('order_records')
    op.drop_table('order_intents')
    op.drop_table('strategy_signals')
    op.drop_table('risk_events')
    op.drop_table('position_snapshots')
    op.drop_table('pnl_snapshots')
    # ### end Alembic commands ###
